spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/emiteai
    username: emiteai
    password: emiteai
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  rabbitmq:
    host: rabbit
